# Generated by Django 5.0.6 on 2024-06-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_utilisateur_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
